### ISSUE TITLE
Birthday list is empty

### ISSUE THREAD

**Issue by wenderreis** [mobeigi/fb2cal#41] opened 2019-09-22 02:59 UTC
I was getting that  domops error so I changed all www.facebook.com to web.facebook.com
I still cannot get it to work. It doesn't find any birthday on my list.

[2019-09-21 23:56:43,703] fb2cal INFO (<module>) Starting fb2cal v1.0.3 (Production) [https://git.io/fjMwr]
[2019-09-21 23:56:43,703] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2019-09-21 23:56:43,704] fb2cal INFO (main) Attemping to parse config file config.ini...
[2019-09-21 23:56:43,705] fb2cal INFO (main) Config successfully loaded.
[2019-09-21 23:56:43,706] fb2cal INFO (main) Logging level set to: INFO
[2019-09-21 23:56:43,706] fb2cal INFO (main) Attemping to authenticate with Facebook...
[2019-09-21 23:56:48,353] fb2cal INFO (main) Successfully authenticated with Facebook.
[2019-09-21 23:56:48,353] fb2cal INFO (main) Fetching all Birthdays via async endpoint...
[2019-09-21 23:56:48,355] fb2cal INFO (get_async_birthdays) Processing birthdays for month September.
[2019-09-21 23:56:51,013] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month September.
[2019-09-21 23:56:51,013] fb2cal INFO (get_async_birthdays) Processing birthdays for month October.
[2019-09-21 23:56:51,359] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month October.
[2019-09-21 23:56:51,360] fb2cal INFO (get_async_birthdays) Processing birthdays for month November.
[2019-09-21 23:56:51,665] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month November.
[2019-09-21 23:56:51,665] fb2cal INFO (get_async_birthdays) Processing birthdays for month December.
[2019-09-21 23:56:51,974] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month December.
[2019-09-21 23:56:51,975] fb2cal INFO (get_async_birthdays) Processing birthdays for month January.
[2019-09-21 23:56:52,296] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month January.
[2019-09-21 23:56:52,296] fb2cal INFO (get_async_birthdays) Processing birthdays for month February.
[2019-09-21 23:56:52,582] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month February.
[2019-09-21 23:56:52,582] fb2cal INFO (get_async_birthdays) Processing birthdays for month March.
[2019-09-21 23:56:52,902] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month March.
[2019-09-21 23:56:52,902] fb2cal INFO (get_async_birthdays) Processing birthdays for month April.
[2019-09-21 23:56:53,191] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month April.
[2019-09-21 23:56:53,192] fb2cal INFO (get_async_birthdays) Processing birthdays for month May.
[2019-09-21 23:56:53,509] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month May.
[2019-09-21 23:56:53,509] fb2cal INFO (get_async_birthdays) Processing birthdays for month June.
[2019-09-21 23:56:53,809] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month June.
[2019-09-21 23:56:53,809] fb2cal INFO (get_async_birthdays) Processing birthdays for month July.
[2019-09-21 23:56:54,120] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month July.
[2019-09-21 23:56:54,120] fb2cal INFO (get_async_birthdays) Processing birthdays for month August.
[2019-09-21 23:56:54,449] fb2cal INFO (get_async_birthdays) Found 0 birthdays for month August.
[2019-09-21 23:56:54,450] fb2cal WARNING (main) Birthday list is empty. Failed to fetch any birthdays.
Traceback (most recent call last):
  File "src/fb2cal.py", line 813, in <module>
  File "src/fb2cal.py", line 120, in main
SystemError

**Comment by mobeigi** [comment] 2019-09-22 03:37
Hey, just to confirm, when you visit:
https://www.facebook.com/events/birthdays/

In your browser, you see the birthday bubble heads with no issues?

Could you turn on `DEBUG` level logging in the config file and post the log here? It might help us find the root cause.

**Comment by wenderreis** [comment] 2019-10-04 14:21
>Hey, just to confirm, when you visit:
https://www.facebook.com/events/birthdays/
In your browser, you see the birthday bubble heads with no issues?

Yes, normal.

>Could you turn on DEBUG level logging in the config file and post the log here? It might help us find the root cause.

[2019-10-04 11:20:01,559] fb2cal INFO (<module>) Starting fb2cal v1.0.3 (Production) [https://git.io/fjMwr]
[2019-10-04 11:20:01,559] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2019-10-04 11:20:01,560] fb2cal INFO (main) Attemping to parse config file config.ini...
[2019-10-04 11:20:01,561] fb2cal INFO (main) Config successfully loaded.
[2019-10-04 11:20:01,562] fb2cal INFO (main) Logging level set to: DEBUG
[2019-10-04 11:20:01,562] fb2cal INFO (main) Attemping to authenticate with Facebook...
[2019-10-04 11:20:01,564] urllib3.connectionpool DEBUG (_new_conn) Starting new HTTP connection (1): web.facebook.com:80
[2019-10-04 11:20:02,017] urllib3.connectionpool DEBUG (_make_request) http://web.facebook.com:80 "GET /login.php HTTP/1.1" 302 0
[2019-10-04 11:20:02,025] urllib3.connectionpool DEBUG (_new_conn) Starting new HTTPS connection (1): web.facebook.com:443
[2019-10-04 11:20:02,640] urllib3.connectionpool DEBUG (_make_request) https://web.facebook.com:443 "GET /login.php HTTP/1.1" 302 0
[2019-10-04 11:20:02,642] urllib3.connectionpool DEBUG (_new_conn) Starting new HTTPS connection (1): www.facebook.com:443
[2019-10-04 11:20:03,321] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "GET /login.php?_rdc=1&_rdr HTTP/1.1" 200 None
[2019-10-04 11:20:03,651] urllib3.connectionpool DEBUG (_make_request) http://web.facebook.com:80 "GET /login.php HTTP/1.1" 302 0
[2019-10-04 11:20:03,835] urllib3.connectionpool DEBUG (_make_request) https://web.facebook.com:443 "GET /login.php HTTP/1.1" 302 0
[2019-10-04 11:20:04,095] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "GET /login.php?_rdc=1&_rdr HTTP/1.1" 200 None
[2019-10-04 11:20:04,815] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "POST /login/device-based/regular/login/?login_attempt=1&lwv=100 HTTP/1.1" 302 0
[2019-10-04 11:20:05,007] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "GET / HTTP/1.1" 200 None
[2019-10-04 11:20:06,722] fb2cal INFO (main) Successfully authenticated with Facebook.
[2019-10-04 11:20:06,722] fb2cal INFO (main) Fetching all Birthdays via async endpoint...
[2019-10-04 11:20:06,725] fb2cal DEBUG (get_next_12_month_epoch_timestamps) Epoch timestamps are: [1569913200, 1572591600, 1575187200, 1577865600, 1580544000, 1583049600, 1585724400, 1588316400, 1590994800, 1593586800, 1596265200, 1598943600]
[2019-10-04 11:20:06,725] fb2cal INFO (get_async_birthdays) Processing birthdays for month October.
[2019-10-04 11:20:06,992] urllib3.connectionpool DEBUG (_make_request) https://web.facebook.com:443 "GET /events/birthdays/ HTTP/1.1" 302 0
[2019-10-04 11:20:07,782] urllib3.connectionpool DEBUG (_make_request) https://www.facebook.com:443 "GET /events/birthdays/?_rdc=1&_rdr HTTP/1.1" 200 None
[2019-10-04 11:20:08,577] urllib3.connectionpool DEBUG (_make_request) https://web.facebook.com:443 "GET /async/birthdays/?date=1569913200&fb_dtsg_ag=AQykl6ypAbyOpjBNjMt3Yhv1bKdDno2-V7xVN9Lwn46oCA%3AAQz6ArUoT7j6CpdS3y90rvjMsmFUVAVFfb5YY-BzHCBLFw&__a=1 HTTP/1.1" 200 None
[2019-10-04 11:20:08,578] fb2cal DEBUG (parse_birthday_async_output) {'redirect': 'https://www.facebook.com/async/birthdays/?date=1569913200&fb_dtsg_ag=AQykl6ypAbyOpjBNjMt3Yhv1bKdDno2-V7xVN9Lwn46oCA%3AAQz6ArUoT7j6CpdS3y90rvjMsmFUVAVFfb5YY-BzHCBLFw&_rdc=1&__a=1&__m_async_page__=1&jazoest=27925&_rdr'}
[2019-10-04 11:20:08,578] fb2cal ERROR (parse_birthday_async_output) KeyError: 'domops'

**Comment by mobeigi** [comment] 2019-10-10 10:22
Looks like you are still getting the **domops** error.
This is dupe of #32

**Closed by mobeigi** 2019-10-10 10:22 UTC
Labels: question

**Comment by antoinekondoh** [comment] 2020-05-11 16:09
hello there. I am currently facing this very problem. i've attached my log file. 
[fb2cal.log](https://github.com/mobeigi/fb2cal/files/4610736/fb2cal.log)

**Comment by ol-khoma** [comment] 2021-04-28 10:00
Hi! I am having this issue as well. However my [log file](https://github.com/mobeigi/fb2cal/files/6390937/fb2cal.log) looks different from the aforementioned ones.
