### ISSUE TITLE
Failed to authenticate with Facebook

### ISSUE THREAD

**Issue by LightOffPro** [mobeigi/fb2cal#16] opened 2019-07-30 20:33 UTC
Script runs successfully, authentication flow completes.

But no ics file is created, "Failed to authenticate with Facebook. Please check provided email/password"

Had 2FA on, but turned it off. Same error occurs. Triple checked login info, and login info is correct.

**Comment by 3rasernl** [comment] 2019-07-30 21:49
Check your out.txt does it have something similar to the following line?
Cookies are disabled in your browser. Enable cookies in the browser settings to continue.

**Comment by mobeigi** [comment] 2019-07-31 01:19
There is currently no useful logging until #12 is implemented.

@3rasernl the base code does not write to any files.

@LightOffPro can you add the following code to `fb2cal.py` undernearth  
`response = login(browser, config['AUTH']['FB_EMAIL'], config['AUTH']['FB_PASS'])`
https://github.com/mobeigi/fb2cal/blob/master/src/fb2cal.py#L80

Add the following lines:
```
with open('out.html', 'w', encoding="utf-8") as f:
  f.write(response.text)
```

Then open the html file with your browser and post a picture of what is being displayed.

**Comment by LightOffPro** [comment] 2019-08-01 10:39
TabErrors when running, likely i am adding the lines wrong. Not too familiar with python or coding at all. One unexpected incident after trying to add the lines properly.

TabError: inconsistent use of tabs and spaces in indentation
PS C:\Users\User\Desktop\fb2cal-1.0.1\src> python ./fb2cal.py
  File "./fb2cal.py", line 82
    if response.status_code != 200:
    ^
IndentationError: unexpected indent
PS C:\Users\User\Desktop\fb2cal-1.0.1\src> python ./fb2cal.py
  File "./fb2cal.py", line 83
    if response.status_code != 200:
    ^
IndentationError: unexpected indent

**Comment by 3rasernl** [comment] 2019-08-01 10:48
Indentation error means a wrong tab or space. It should look like this:

    # Attempt login
    response = login(browser, config['AUTH']['FB_EMAIL'], config['AUTH']['FB_PASS'])
    with open('out.html', 'w', encoding="utf-8") as f:
      f.write(response.text)
    if response.status_code != 200:
        sys.exit(f'Failed to authenticate with Facebook. Status code: {response.status_code}.')

**Comment by LightOffPro** [comment] 2019-08-01 10:57
> Indentation error means a wrong tab or space. It should look like this:
> 
> ```
> # Attempt login
> response = login(browser, config['AUTH']['FB_EMAIL'], config['AUTH']['FB_PASS'])
> with open('out.html', 'w', encoding="utf-8") as f:
>   f.write(response.text)
> if response.status_code != 200:
>     sys.exit(f'Failed to authenticate with Facebook. Status code: {response.status_code}.')
> ```

Adding the lines give out this error, not sure if i am still mispositioning the new lines.

PS C:\Users\User\Desktop\fb2cal-master\src> python ./fb2cal.py
Traceback (most recent call last):
  File "./fb2cal.py", line 79, in <module>
    response = login(browser, config['AUTH']['FB_EMAIL'], config['AUTH']['FB_PASS'])
NameError: name 'login' is not defined

**Comment by 3rasernl** [comment] 2019-08-01 11:09
[fb2cal.zip](https://github.com/mobeigi/fb2cal/files/3456348/fb2cal.zip)


replace the fb2cal.py with the one in this zipfile

**Comment by LightOffPro** [comment] 2019-08-01 11:16
> [fb2cal.zip](https://github.com/mobeigi/fb2cal/files/3456348/fb2cal.zip)
> 
> replace the fb2cal.py with the one in this zipfile

Same authentication problem, out.html on Chrome opens a facebook page displaying that cookies are needed.

**Comment by mobeigi** [comment] 2019-08-01 14:43
Looks like a duplicate of #4 . Follow that issue for updates.

**Closed by mobeigi** 2019-08-01 14:43 UTC
Labels: duplicate, question
