### ISSUE TITLE
Accented characters

### ISSUE THREAD

**Issue by gioluca2** [mobeigi/fb2cal#29] opened 2019-08-09 14:26 UTC
I have this strange error: if I open google calendar on pc accented characters are displayed correctly, but in samsung calendar on my galaxy s8 I see "&#xf2" instead of "ò".
How can I solve this issue?

**Comment by mobeigi** [comment] 2019-08-10 03:32
Yeah it is a known issue.

Duplicate of: https://github.com/mobeigi/fb2cal/issues/25

**Closed by mobeigi** 2019-08-10 03:32 UTC
Labels: duplicate
