### ISSUE TITLE
AttributeError: 'Calendar' object has no attribute '_unused'

### ISSUE THREAD

**Issue by andrewwulf** [mobeigi/fb2cal#46] opened 2019-10-29 03:04 UTC
fb2cal INFO (main) Creating birthday ICS file...
Traceback (most recent call last):
  File "fb2cal.py", line 813, in <module>
    main()
  File "fb2cal.py", line 126, in main
    c = populate_birthdays_calendar(birthdays)
  File "fb2cal.py", line 782, in populate_birthdays_calendar
    c._unused.append(ics.parse.ContentLine(name='X-WR-CALNAME', params={}, value='Facebook Birthdays (fb2cal)'))
AttributeError: 'Calendar' object has no attribute '_unused'

**Comment by mobeigi** [comment] 2019-10-29 04:00
Duplicate of https://github.com/mobeigi/fb2cal/issues/44

Please clone latest version of code and update ics module to latest version (`0.6+`)

**Closed by mobeigi** 2019-10-29 04:00 UTC
Labels: duplicate
