### ISSUE TITLE
2FA doesn't work, not even with app-password

### ISSUE THREAD

**Issue by JoSSte** [mobeigi/fb2cal#105] opened 2021-08-10 18:38 UTC
With 2FA activated, his script just fails with `Failed to authenticate with Facebook with email {email}. Please check provided email/password.`  

App-Password article on fb help:
https://www.facebook.com/help/249378535085386/

**Comment by JoSSte** [comment] 2021-08-10 19:11
I Re-read the docs and discovered that I had missed the "no quotes" comment in the fill out `config/config.ini` step. didn't help though...

**Comment by JoSSte** [comment] 2021-08-10 19:13
verified that the script works with user with no 2fa enabled - works beautifully

**Comment by mobeigi** [comment] 2021-08-11 14:12
This is a duplicate of https://github.com/mobeigi/fb2cal/issues/9 and also mentioned in the README.
2FA isn't supported at all right now. Glad it worked with no 2FA for you 👍

**Closed by mobeigi** 2021-08-11 14:12 UTC
