### ISSUE TITLE
Authentication error with special characters in a password

### ISSUE THREAD

**Issue by aalyokhin** [mobeigi/fb2cal#49] opened 2019-12-19 16:12 UTC
Hi.

I was struggling to make it work, getting `Failed to authenticate with Facebook with email ***@gmail.com. Please check provided email/password`. Re-checked the credentials multiple times and found out what's going on only after printing the password to a console.

I have the following symbols in my password – `%%`, which were recognized as `%` by the script.  After changing it in the config to `%%%%` I was able to proceed. Not sure if this is the case with other special characters, but that's how it is with percent one.

**Comment by mobeigi** [comment] 2019-12-20 04:14
Dupe of #37 . 

Maybe a helpful note/comment should be added somewhere.

**Closed** 2020-01-12 03:26 UTC
Labels: duplicate, enhancement, question
