### ISSUE TITLE
KEY ERROR: DoMops

### ISSUE THREAD

**Issue by Link2Adi** [mobeigi/fb2cal#62] opened 2020-05-04 11:08 UTC
I get the following error when I run the program. Please assist if I have been doing something wrong.

```
[2020-05-04 13:06:19,154] fb2cal INFO (<module>) Starting fb2cal v1.0.4 (Production) [https://git.io/fjMwr]
[2020-05-04 13:06:19,155] fb2cal INFO (<module>) This project is released under the GPLv3 license.
[2020-05-04 13:06:19,155] fb2cal INFO (main) Attemping to parse config file config.ini...
[2020-05-04 13:06:19,156] fb2cal INFO (main) Config successfully loaded.
[2020-05-04 13:06:19,156] fb2cal INFO (main) Logging level set to: INFO
[2020-05-04 13:06:19,157] fb2cal INFO (main) Authenticating with Google Drive API...
[2020-05-04 13:06:19,162] googleapiclient.discovery INFO (_retrieve_discovery_doc) URL being requested: GET https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
[2020-05-04 13:06:20,891] fb2cal INFO (main) Successfully authenticated with Google Drive API.
[2020-05-04 13:06:20,892] fb2cal INFO (main) Attemping to authenticate with Facebook...
[2020-05-04 13:06:26,546] fb2cal INFO (main) Successfully authenticated with Facebook.
[2020-05-04 13:06:26,547] fb2cal INFO (main) Fetching all Birthdays via async endpoint...
[2020-05-04 13:06:26,554] fb2cal INFO (get_async_birthdays) Processing birthdays for month May.
[2020-05-04 13:06:28,362] fb2cal ERROR (parse_birthday_async_output) KeyError: 'domops'
Traceback (most recent call last):
  File "C:\Users\Link2\Documents\Adi\fb2cal-master\src\fb2cal.py", line 443, in parse_birthday_async_output
    birthday_card_html = json_response['domops'][0][3]['__html']
KeyError: 'domops'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Link2\Documents\Adi\fb2cal-master\src\fb2cal.py", line 815, in <module>
    main()
  File "C:\Users\Link2\Documents\Adi\fb2cal-master\src\fb2cal.py", line 117, in main
    birthdays = get_async_birthdays(browser)
  File "C:\Users\Link2\Documents\Adi\fb2cal-master\src\fb2cal.py", line 401, in get_async_birthdays
    birthdays_for_month = parse_birthday_async_output(browser, response.text)
  File "C:\Users\Link2\Documents\Adi\fb2cal-master\src\fb2cal.py", line 451, in parse_birthday_async_output
    raise SystemError
SystemError
```

**Comment by mobeigi** [comment] 2020-05-05 09:42
Duplicate of #32 . 

Please discuss there.

**Closed by mobeigi** 2020-05-05 09:42 UTC
Labels: duplicate
