### ISSUE TITLE
Handle Cyrillic letter names 

### ISSUE THREAD

**Issue by AleksandarAleksandrov** [mobeigi/fb2cal#28] opened 2019-08-09 11:42 UTC
When I run the application and have people who's names contain Cyrillic letters, the following data gets saved in the `.ics` file 

```
SUMMARY:&#x41d\;&#x438\;&#x43d\;&#x430\; &#x41f\;&#x435\;&#x442\;&#x440\;&#x43e\;&#x432\;&#x430\;'s Birthday
```
 And the same text is displayed later on in the actual calendar.

Shouldn't the saved names be encoded in `UTF-8` ?

PS: Thanks for this product very, very much 😄

**Comment by mobeigi** [comment] 2019-08-09 12:57
Yes they should be!

Duplicate of: #25

**Closed by mobeigi** 2019-08-09 12:57 UTC
Labels: duplicate
